version: '3.8' 
services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: unirome
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: